const translations = {
  zh: {
    brand: "老王跟小宋工作室",
    navServices: "服务",
    navAI: "AI",
    navWork: "作品",
    navProducts: "产品",
    navFenshenyun: "分身云",
    navDownload: "下载",
    navBusiness: "合作",
    navProcess: "流程",
    navContact: "联系",
    heroTitle: "我们开发<br>西班牙生活通",
    heroCopy: "面向西班牙华人社区的本地生活服务平台，把招工、租房、生意转让、二手和生活服务放到一个清楚好用的地方。",
    heroSubcopy: "选择语言继续浏览。Choose your language. Elige tu idioma.",
    visitProduct: "访问产品",
    downloadApp: "下载手机版",
    viewCase: "查看案例",
    introTitle: "从社区真实需求里长出来的产品。",
    introCopy: "西班牙生活通服务在西班牙生活、工作和经营的华人用户。我们把高频本地信息整理成可发布、可搜索、可筛选的数字产品，让找工作、找房、找服务和做生意的人更快连接起来。",
    introPoint1: "<strong>English</strong>We design and develop practical web products for local communities, from idea and interface to launch and iteration.",
    introPoint2: "<strong>Español</strong>Diseñamos y desarrollamos productos web útiles para comunidades locales, desde la idea y la interfaz hasta el lanzamiento y la mejora continua.",
    servicesTitle: "我们负责的不只是页面",
    service1Title: "产品规划",
    service1Copy: "从社区场景、用户角色和发布流程出发，整理真正需要的功能优先级。",
    service2Title: "网站开发",
    service2Copy: "搭建可访问、可分享、可持续更新的 Web 产品与移动端体验。",
    service3Title: "信息系统",
    service3Copy: "支持分类、筛选、发布、账号、会员和信息管理等本地服务平台能力。",
    service4Title: "AI 与增长落地",
    service4Copy: "结合人工智能、多语言内容、微信分享、搜索呈现和转化路径，让产品真的被使用。",
    aiTitle: "把人工智能放进真实业务里。",
    aiCopy: "我们关注的不是为了 AI 而 AI，而是用人工智能提升信息整理、多语言沟通、内容运营和用户匹配效率，让本地服务平台更聪明也更省力。",
    ai1Title: "多语言内容辅助",
    ai1Copy: "辅助中文、英语、西班牙语内容生成与优化，让商家和用户沟通更顺。",
    ai2Title: "信息分类与审核",
    ai2Copy: "帮助分类信息更快归类、整理和发现异常内容，降低平台运营成本。",
    ai3Title: "智能搜索与匹配",
    ai3Copy: "围绕招聘、房产、服务和商家需求，探索更自然的搜索与推荐体验。",
    workTitle: "西班牙生活通",
    caseTitle: "西班牙华人生活服务平台",
    caseCopy: "面向西班牙华人社区的分类信息产品，覆盖招工求职、租房买房、生意转让、二手物品和生活服务等高频本地需求。",
    caseSubcopy: "一个连接本地信息、商家服务和社区需求的线上平台。",
    openProduct: "打开产品",
    productsTitle: "我们正在形成一组可销售的软件产品",
    productsCopy: "工作室不只做一次性网页，也会把真实业务需求沉淀成可交付、可买断、可维护的软件。下面是当前产品矩阵，后续开发的新软件也会继续加入这里。",
    productLive: "已上线",
    productSale: "买断销售",
    productPrivate: "私有数据",
    lifeTitle: "西班牙生活通",
    lifeCopy: "面向西班牙华人社区的本地生活分类信息平台，覆盖招工求职、租房买房、生意转让、二手物品和生活服务。",
    lifeFeature1: "分类信息发布、搜索、筛选和城市浏览",
    lifeFeature2: "商家推广、平台合作和社区流量入口",
    lifeFeature3: "适合西班牙本地华人服务场景长期运营",
    lifeAction: "打开产品",
    fsyTitle: "分身云屏播",
    fsyCopy: "面向餐饮、服装、零售和本地生活门店的商业广告投屏系统。商家用手机修改文字、图片、价格和广告信息，一键发送到安卓电视棒，电视屏幕自动播放最新广告。",
    fsyFeature1: "手机控制端：老板或店员直接改广告",
    fsyFeature2: "电视棒播放端：插入电视 HDMI 即可播放",
    fsyFeature3: "支持单店买断、多屏授权和年度维护",
    fsyAction: "查看产品和下载",
    fsyControlTitle: "手机控制端",
    fsyControlCopy: "老板或店员可以在手机上选择模板、改价格、换图片、发布优惠活动。",
    fsyTvTitle: "电视棒播放端",
    fsyTvCopy: "安卓电视棒插入电视 HDMI，输入屏幕码后持续播放门店广告。",
    fsyBusinessTitle: "买断版交付",
    fsyBusinessCopy: "支持单店买断、多屏授权和年度维护，适合门店老板和广告屏工程商销售。",
    fsyContact: "咨询分身云屏播",
    fsyCoop: "合作销售",
    propertyTitle: "西班牙个人物业管理系统",
    propertyCopy: "面向西班牙房产持有者和物业服务团队，把资产、租客、租金、费用、文件、报税资料和客户订阅集中管理。",
    propertyFeature1: "房产、租客、合同、收入和费用管理",
    propertyFeature2: "IRPF、IVA、Modelo 303/390/180 报税参考",
    propertyFeature3: "文件、发票、报表、Excel/PDF 导出和本地智能体接口",
    propertyAction: "咨询物业系统",
    productsNote: "后续新增软件会继续按“产品定位、使用对象、核心功能、销售方式、交付方式”加入这里，方便客户直接理解工作室能提供什么。",
    downloadTitle: "连接网页版，预留安卓下载入口",
    downloadCopy: "西班牙生活通现在先以网页版运行，方便快速测试、收集反馈和稳定功能。等产品稳定后，安卓 APK 会放在这个页面供用户下载和安装。",
    webLive: "已连接",
    webAppTitle: "西班牙生活通网页版",
    webAppCopy: "直接打开网页使用，手机和电脑都可以访问。",
    openWebApp: "打开网页版",
    androidPreparing: "稳定版准备中",
    androidTitle: "Android 安卓手机版",
    androidCopy: "稳定后将提供 APK 下载，文件预留位置：downloads/espanalife-android.apk。",
    androidComingSoon: "稳定版准备中",
    rowJobs: "招工求职",
    rowHousing: "租房买房",
    rowBusiness: "生意转让",
    rowMarketplace: "二手与生活服务",
    businessTitle: "商务合作",
    businessCopy: "面向西班牙本地商家、服务机构、社区组织和项目方，我们可以一起做信息发布、品牌露出、平台合作和定制化数字产品。",
    business1Title: "商家入驻与推广",
    business1Copy: "帮助本地商家在西班牙华人社区里获得更清楚的展示入口。",
    business2Title: "平台资源合作",
    business2Copy: "围绕招聘、房产、生活服务、生意转让等场景展开内容与流量合作。",
    business3Title: "产品定制开发",
    business3Copy: "为具体社区、行业或本地服务场景设计并开发独立网站或工具。",
    businessNote1: "English: partnerships, local merchant promotion, platform cooperation and custom product development.",
    businessNote2: "Español: colaboraciones comerciales, promoción para negocios locales, cooperación de plataforma y desarrollo de productos a medida.",
    processTitle: "从需求到上线运营",
    process1Title: "识别场景",
    process1Copy: "先看用户每天真正要完成什么事，再决定产品应该长什么样。",
    process2Title: "搭建功能",
    process2Copy: "围绕发布、搜索、筛选、账号和管理，把核心链路做完整。",
    process3Title: "优化体验",
    process3Copy: "让手机端访问、微信分享、城市分类和信息浏览都更顺手。",
    process4Title: "上线迭代",
    process4Copy: "上线后继续根据用户反馈、内容质量和运营节奏调整产品。",
    contactTitle: "商务合作，或想做一个真正有人用的产品？",
    contactCopy: "欢迎联系老王跟小宋工作室。我们可以从商家推广、平台合作、社区项目或一个本地服务场景开始，把想法推进到可上线、可运营的产品。",
    wechatLabel: "微信 WeChat",
    wechatHint: "点击微信号会复制微信号，并尝试打开微信。",
    wechatCopied: "已复制微信号 esvida168，正在尝试打开微信。",
    mobileProduct: "产品",
    mobileDownload: "下载",
    mobileBusiness: "合作",
    mobileContact: "联系"
  },
  en: {
    brand: "Wang & Song Studio",
    navServices: "Services",
    navAI: "AI",
    navWork: "Work",
    navProducts: "Products",
    navFenshenyun: "Fenshenyun",
    navDownload: "Download",
    navBusiness: "Partnerships",
    navProcess: "Process",
    navContact: "Contact",
    heroTitle: "We build<br>España Life",
    heroCopy: "A local service platform for the Chinese community in Spain, bringing jobs, housing, business transfers, second-hand listings and everyday services into one clear product.",
    heroSubcopy: "Language selected: English.",
    visitProduct: "Visit Product",
    downloadApp: "Mobile Download",
    viewCase: "View Case",
    introTitle: "Products shaped by real community needs.",
    introCopy: "España Life serves Chinese users living, working and running businesses in Spain. We turn high-frequency local information into a product that is easy to publish, search and filter.",
    introPoint1: "<strong>Studio Focus</strong>Practical web products for local communities, from strategy and interface to launch and iteration.",
    introPoint2: "<strong>Commercial Fit</strong>Built for real use: local discovery, merchant visibility, community information and repeatable operations.",
    servicesTitle: "More than a website",
    service1Title: "Product Planning",
    service1Copy: "We clarify users, scenarios and publishing flows before deciding what should be built first.",
    service2Title: "Web Development",
    service2Copy: "We build accessible, shareable and maintainable web products with strong mobile experiences.",
    service3Title: "Information Systems",
    service3Copy: "Categories, filters, posting, accounts, memberships and listing management for local service platforms.",
    service4Title: "AI and Growth",
    service4Copy: "We combine AI, multilingual content, WeChat sharing, search visibility and conversion paths to help products get used.",
    aiTitle: "AI for real business workflows.",
    aiCopy: "We do not add AI for decoration. We use artificial intelligence to improve information organization, multilingual communication, content operations and user matching for local service platforms.",
    ai1Title: "Multilingual Content Assistance",
    ai1Copy: "Support Chinese, English and Spanish content creation and refinement so merchants and users communicate more smoothly.",
    ai2Title: "Listing Classification and Review",
    ai2Copy: "Help classify, organize and detect unusual listing content faster, reducing operational workload.",
    ai3Title: "Smart Search and Matching",
    ai3Copy: "Explore more natural search and recommendation experiences for jobs, housing, services and merchant needs.",
    workTitle: "España Life",
    caseTitle: "Local service platform for Chinese users in Spain",
    caseCopy: "A classified information product covering jobs, housing, business transfers, second-hand goods and everyday services.",
    caseSubcopy: "Built to connect local information, merchant services and community needs.",
    openProduct: "Open Product",
    productsTitle: "We are building a suite of sellable software products",
    productsCopy: "The studio does not only build one-off websites. We turn real business needs into software that can be delivered, licensed, maintained and sold. New products will continue to be added here.",
    productLive: "Live",
    productSale: "Buyout Sale",
    productPrivate: "Private Data",
    lifeTitle: "Espana Life",
    lifeCopy: "A local classifieds and service platform for the Chinese community in Spain, covering jobs, housing, business transfers, second-hand goods and everyday services.",
    lifeFeature1: "Listing publishing, search, filtering and city browsing",
    lifeFeature2: "Merchant promotion, platform partnerships and community traffic",
    lifeFeature3: "Built for long-term local Chinese service operations in Spain",
    lifeAction: "Open Product",
    fsyTitle: "Fenshenyun ScreenCast",
    fsyCopy: "A commercial digital signage system for restaurants, fashion stores, retailers and local service businesses. Merchants edit text, images, prices and promotions on a phone, then send them to an Android TV stick for automatic playback.",
    fsyFeature1: "Mobile control app for editing ads from a phone",
    fsyFeature2: "TV stick player that plugs into HDMI and keeps playing",
    fsyFeature3: "Single-store buyout, multi-screen licensing and maintenance",
    fsyAction: "View Product and Downloads",
    fsyControlTitle: "Mobile Control App",
    fsyControlCopy: "Owners and staff can choose templates, update prices, replace images and publish promotions from a phone.",
    fsyTvTitle: "TV Stick Player",
    fsyTvCopy: "An Android TV stick plugs into the TV HDMI port, receives a screen code and keeps playing store advertisements.",
    fsyBusinessTitle: "One-time License",
    fsyBusinessCopy: "Supports single-store purchase, multi-screen licensing and yearly maintenance for store owners and signage installers.",
    fsyContact: "Ask About Fenshenyun",
    fsyCoop: "Sales Partnership",
    propertyTitle: "Iberia Asset Cloud",
    propertyCopy: "A property-management system for Spanish property owners and service teams, centralizing assets, tenants, rent, expenses, files, tax references and customer subscriptions.",
    propertyFeature1: "Properties, tenants, contracts, income and expense records",
    propertyFeature2: "IRPF, IVA, Modelo 303/390/180 tax reference workflows",
    propertyFeature3: "Documents, invoices, reports, Excel/PDF export and local agent connectors",
    propertyAction: "Ask About Property System",
    productsNote: "Future software can be added here using the same structure: positioning, audience, core functions, sales model and delivery model.",
    downloadTitle: "Web app connected, Android download reserved",
    downloadCopy: "Espana Life runs as a web app first so the product can be tested, improved and stabilized quickly. When the Android version is ready, the APK download will be published here.",
    webLive: "Connected",
    webAppTitle: "Espana Life Web App",
    webAppCopy: "Open the web app directly from any phone or computer.",
    openWebApp: "Open Web App",
    androidPreparing: "Stable build in progress",
    androidTitle: "Android Mobile App",
    androidCopy: "After stabilization, the APK will be available at downloads/espanalife-android.apk.",
    androidComingSoon: "Stable build in progress",
    rowJobs: "Jobs & Hiring",
    rowHousing: "Housing",
    rowBusiness: "Business Transfers",
    rowMarketplace: "Second-hand & Services",
    businessTitle: "Business Partnerships",
    businessCopy: "For local businesses, service providers, community organizations and project owners in Spain, we support listings, brand visibility, platform partnerships and custom digital products.",
    business1Title: "Merchant Promotion",
    business1Copy: "Give local businesses a clearer way to reach the Chinese community in Spain.",
    business2Title: "Platform Partnerships",
    business2Copy: "Collaborate around jobs, real estate, local services, business transfers and community traffic.",
    business3Title: "Custom Product Development",
    business3Copy: "Design and build independent websites or tools for specific communities, industries or local service scenarios.",
    businessNote1: "Available for partnerships, local merchant promotion, platform cooperation and custom product development.",
    businessNote2: "Spanish and Chinese community markets can be connected through focused digital products.",
    processTitle: "From need to launch",
    process1Title: "Identify the Scenario",
    process1Copy: "We start with what users actually need to do every day.",
    process2Title: "Build the Core",
    process2Copy: "Publishing, search, filters, accounts and management are built as a complete product path.",
    process3Title: "Improve the Experience",
    process3Copy: "Mobile access, sharing, city categories and browsing details are tuned for real users.",
    process4Title: "Launch and Iterate",
    process4Copy: "After launch, we continue improving based on feedback, content quality and operations.",
    contactTitle: "Business partnership or a product people will actually use?",
    contactCopy: "Contact Wang & Song Studio. We can start from merchant promotion, platform cooperation, community projects or a local service scenario.",
    wechatLabel: "WeChat",
    wechatHint: "Tap the WeChat ID to copy it and try opening WeChat.",
    wechatCopied: "WeChat ID esvida168 copied. Trying to open WeChat.",
    mobileProduct: "Product",
    mobileDownload: "Download",
    mobileBusiness: "Partner",
    mobileContact: "Contact"
  },
  es: {
    brand: "Wang & Song Studio",
    navServices: "Servicios",
    navAI: "IA",
    navWork: "Proyectos",
    navProducts: "Productos",
    navFenshenyun: "Fenshenyun",
    navDownload: "Descargar",
    navBusiness: "Colaboración",
    navProcess: "Proceso",
    navContact: "Contacto",
    heroTitle: "Creamos<br>España Life",
    heroCopy: "Una plataforma local de servicios para la comunidad china en España, con empleo, vivienda, traspasos de negocios, segunda mano y servicios cotidianos en un solo producto.",
    heroSubcopy: "Idioma seleccionado: Español.",
    visitProduct: "Ver Producto",
    downloadApp: "Descargar Movil",
    viewCase: "Ver Caso",
    introTitle: "Productos nacidos de necesidades reales de la comunidad.",
    introCopy: "España Life ayuda a usuarios chinos que viven, trabajan o tienen negocios en España. Convertimos información local frecuente en un producto fácil de publicar, buscar y filtrar.",
    introPoint1: "<strong>Enfoque del estudio</strong>Productos web prácticos para comunidades locales, desde la estrategia y la interfaz hasta el lanzamiento y la iteración.",
    introPoint2: "<strong>Valor comercial</strong>Diseñado para uso real: descubrimiento local, visibilidad para comercios, información comunitaria y operación continua.",
    servicesTitle: "Más que una página web",
    service1Title: "Planificación de Producto",
    service1Copy: "Definimos usuarios, escenarios y flujos de publicación antes de decidir qué construir primero.",
    service2Title: "Desarrollo Web",
    service2Copy: "Creamos productos web accesibles, compartibles y mantenibles, con una experiencia móvil sólida.",
    service3Title: "Sistemas de Información",
    service3Copy: "Categorías, filtros, publicación, cuentas, membresías y gestión de anuncios para plataformas locales.",
    service4Title: "IA y Crecimiento",
    service4Copy: "Combinamos inteligencia artificial, contenido multilingüe, WeChat, buscadores, campañas y caminos de conversión.",
    aiTitle: "Inteligencia artificial aplicada al negocio real.",
    aiCopy: "No usamos IA como adorno. La aplicamos para mejorar la organización de información, la comunicación multilingüe, la operación de contenidos y la conexión entre usuarios en plataformas locales.",
    ai1Title: "Asistencia de Contenido Multilingüe",
    ai1Copy: "Apoyo para crear y mejorar contenido en chino, inglés y español, facilitando la comunicación entre comercios y usuarios.",
    ai2Title: "Clasificación y Revisión",
    ai2Copy: "Ayuda a clasificar, ordenar y detectar contenido anómalo en anuncios, reduciendo el trabajo operativo.",
    ai3Title: "Búsqueda y Matching Inteligente",
    ai3Copy: "Exploramos experiencias de búsqueda y recomendación más naturales para empleo, vivienda, servicios y comercios.",
    workTitle: "España Life",
    caseTitle: "Plataforma local de servicios para usuarios chinos en España",
    caseCopy: "Producto de anuncios clasificados que cubre empleo, vivienda, traspasos de negocios, segunda mano y servicios cotidianos.",
    caseSubcopy: "Creado para conectar información local, servicios comerciales y necesidades de la comunidad.",
    openProduct: "Abrir Producto",
    productsTitle: "Estamos creando una suite de productos de software vendibles",
    productsCopy: "El estudio no solo crea páginas puntuales. Convertimos necesidades reales de negocio en software que puede entregarse, licenciarse, mantenerse y venderse. Los nuevos productos se añadirán aquí.",
    productLive: "Activo",
    productSale: "Compra única",
    productPrivate: "Datos privados",
    lifeTitle: "Espana Life",
    lifeCopy: "Plataforma local de anuncios y servicios para la comunidad china en España, con empleo, vivienda, traspasos, segunda mano y servicios cotidianos.",
    lifeFeature1: "Publicación, búsqueda, filtros y navegación por ciudad",
    lifeFeature2: "Promoción de comercios, colaboraciones y tráfico comunitario",
    lifeFeature3: "Pensado para operar servicios locales chinos en España a largo plazo",
    lifeAction: "Abrir Producto",
    fsyTitle: "Fenshenyun ScreenCast",
    fsyCopy: "Sistema comercial de pantallas publicitarias para restaurantes, tiendas de moda, comercios minoristas y servicios locales. El negocio edita textos, imágenes, precios y promociones desde el móvil y los envía a un Android TV stick.",
    fsyFeature1: "Control desde móvil para editar anuncios",
    fsyFeature2: "Reproductor TV stick conectado por HDMI",
    fsyFeature3: "Compra por tienda, licencias multipantalla y mantenimiento",
    fsyAction: "Ver producto y descargas",
    fsyControlTitle: "Control desde móvil",
    fsyControlCopy: "El propietario o el personal puede elegir plantillas, cambiar precios, sustituir imágenes y publicar promociones.",
    fsyTvTitle: "Reproductor TV Stick",
    fsyTvCopy: "El Android TV stick se conecta por HDMI, recibe un código de pantalla y reproduce anuncios del comercio.",
    fsyBusinessTitle: "Licencia de compra única",
    fsyBusinessCopy: "Soporta compra para una tienda, licencias multipantalla y mantenimiento anual para comercios e instaladores.",
    fsyContact: "Consultar Fenshenyun",
    fsyCoop: "Colaborar en ventas",
    propertyTitle: "Iberia Asset Cloud",
    propertyCopy: "Sistema para propietarios y equipos de gestión inmobiliaria en España, centralizando activos, inquilinos, alquileres, gastos, documentos, referencias fiscales y suscripciones.",
    propertyFeature1: "Inmuebles, inquilinos, contratos, ingresos y gastos",
    propertyFeature2: "Flujos de referencia fiscal para IRPF, IVA, Modelo 303/390/180",
    propertyFeature3: "Documentos, facturas, informes, exportación Excel/PDF y conectores de agente local",
    propertyAction: "Consultar sistema inmobiliario",
    productsNote: "Los futuros programas se podrán añadir con la misma estructura: posicionamiento, usuarios, funciones, modelo de venta y forma de entrega.",
    downloadTitle: "Web conectada y descarga Android reservada",
    downloadCopy: "Espana Life funciona primero como aplicación web para probar, mejorar y estabilizar el producto. Cuando la version Android este lista, la descarga APK se publicara aqui.",
    webLive: "Conectado",
    webAppTitle: "Espana Life Web",
    webAppCopy: "Abre la version web directamente desde movil u ordenador.",
    openWebApp: "Abrir Web",
    androidPreparing: "Version estable en preparacion",
    androidTitle: "Aplicacion Android",
    androidCopy: "Cuando este estable, el APK estara disponible en downloads/espanalife-android.apk.",
    androidComingSoon: "Version estable en preparacion",
    rowJobs: "Empleo",
    rowHousing: "Vivienda",
    rowBusiness: "Traspasos de Negocios",
    rowMarketplace: "Segunda Mano y Servicios",
    businessTitle: "Colaboración Comercial",
    businessCopy: "Para comercios locales, proveedores de servicios, organizaciones comunitarias y proyectos en España, ofrecemos anuncios, visibilidad de marca, cooperación de plataforma y productos digitales a medida.",
    business1Title: "Promoción para Comercios",
    business1Copy: "Ayudamos a negocios locales a llegar con más claridad a la comunidad china en España.",
    business2Title: "Cooperación de Plataforma",
    business2Copy: "Colaboramos en empleo, vivienda, servicios locales, traspasos de negocios y tráfico comunitario.",
    business3Title: "Desarrollo a Medida",
    business3Copy: "Diseñamos y desarrollamos sitios web o herramientas para comunidades, sectores o servicios locales específicos.",
    businessNote1: "Disponibles para colaboraciones comerciales, promoción local, cooperación de plataforma y desarrollo a medida.",
    businessNote2: "Conectamos mercados locales españoles y comunidades chinas mediante productos digitales enfocados.",
    processTitle: "De la necesidad al lanzamiento",
    process1Title: "Identificar el Escenario",
    process1Copy: "Empezamos por lo que los usuarios realmente necesitan hacer cada día.",
    process2Title: "Construir el Núcleo",
    process2Copy: "Publicación, búsqueda, filtros, cuentas y gestión forman una ruta de producto completa.",
    process3Title: "Mejorar la Experiencia",
    process3Copy: "Optimizamos acceso móvil, compartir, categorías por ciudad y navegación de información.",
    process4Title: "Lanzar e Iterar",
    process4Copy: "Después del lanzamiento, mejoramos según comentarios, calidad del contenido y operación.",
    contactTitle: "¿Colaboración comercial o un producto que la gente use de verdad?",
    contactCopy: "Contacta con Wang & Song Studio. Podemos empezar desde promoción para comercios, cooperación de plataforma, proyectos comunitarios o un servicio local.",
    wechatLabel: "WeChat",
    wechatHint: "Toca el ID de WeChat para copiarlo e intentar abrir WeChat.",
    wechatCopied: "ID de WeChat esvida168 copiado. Intentando abrir WeChat.",
    mobileProduct: "Producto",
    mobileDownload: "Descargar",
    mobileBusiness: "Colaborar",
    mobileContact: "Contacto"
  }
};

const languageNames = {
  zh: "zh-CN",
  en: "en",
  es: "es"
};

function applyLanguage(lang) {
  const dictionary = translations[lang] || translations.zh;

  document.documentElement.lang = languageNames[lang] || "zh-CN";
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) {
      element.innerHTML = dictionary[key];
    }
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    const isActive = button.dataset.lang === lang;
    button.classList.toggle("active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  localStorage.setItem("studioLanguage", lang);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

document.querySelectorAll("[data-wechat-id]").forEach((link) => {
  link.addEventListener("click", async (event) => {
    event.preventDefault();

    const wechatId = link.dataset.wechatId;
    const lang = localStorage.getItem("studioLanguage") || "zh";
    const dictionary = translations[lang] || translations.zh;
    const hint = document.getElementById("wechatHint");

    try {
      await navigator.clipboard.writeText(wechatId);
    } catch (error) {
      // Clipboard access can be blocked in some mobile browsers; still try to open WeChat.
    }

    if (hint) {
      hint.textContent = dictionary.wechatCopied;
    }

    window.location.href = "weixin://";
  });
});

applyLanguage(localStorage.getItem("studioLanguage") || "zh");
