const translations = {
  zh: {
    brand: "老王跟小宋工作室",
    navServices: "服务",
    navWork: "作品",
    navBusiness: "合作",
    navProcess: "流程",
    navContact: "联系",
    heroTitle: "我们开发<br>西班牙生活通",
    heroCopy: "面向西班牙华人社区的本地生活服务平台，把招工、租房、生意转让、二手和生活服务放到一个清楚好用的地方。",
    heroSubcopy: "选择语言继续浏览。Choose your language. Elige tu idioma.",
    visitProduct: "访问产品",
    viewCase: "查看案例",
    introTitle: "从社区真实需求里长出来的产品。",
    introCopy: "西班牙生活通服务在西班牙生活、工作和经营的华人用户。我们把高频本地信息整理成可发布、可搜索、可筛选的数字产品，让找工作、找房、找服务和做生意的人更快连接起来。",
    introPoint1: "<strong>English</strong>We design and develop practical web products for local communities, from idea and interface to launch and iteration.",
    introPoint2: "<strong>Español</strong>Diseñamos y desarrollamos productos web útiles para comunidades locales, desde la idea y la interfaz hasta el lanzamiento y la mejora continua.",
    servicesTitle: "我们负责的不只是页面",
    service1Title: "产品规划",
    service1Copy: "从社区场景、用户角色和发布流程出发，整理真正需要的功能优先级。",
    service2Title: "网站开发",
    service2Copy: "搭建可访问、可分享、可持续更新的 Web 产品与移动端体验。",
    service3Title: "信息系统",
    service3Copy: "支持分类、筛选、发布、账号、会员和信息管理等本地服务平台能力。",
    service4Title: "增长落地",
    service4Copy: "兼顾微信分享、搜索呈现、活动入口和转化路径，让产品真的被使用。",
    workTitle: "西班牙生活通",
    caseTitle: "西班牙华人生活服务平台",
    caseCopy: "面向西班牙华人社区的分类信息产品，覆盖招工求职、租房买房、生意转让、二手物品和生活服务等高频本地需求。",
    caseSubcopy: "一个连接本地信息、商家服务和社区需求的线上平台。",
    openProduct: "打开产品",
    rowJobs: "招工求职",
    rowHousing: "租房买房",
    rowBusiness: "生意转让",
    rowMarketplace: "二手与生活服务",
    businessTitle: "商务合作",
    businessCopy: "面向西班牙本地商家、服务机构、社区组织和项目方，我们可以一起做信息发布、品牌露出、平台合作和定制化数字产品。",
    business1Title: "商家入驻与推广",
    business1Copy: "帮助本地商家在西班牙华人社区里获得更清楚的展示入口。",
    business2Title: "平台资源合作",
    business2Copy: "围绕招聘、房产、生活服务、生意转让等场景展开内容与流量合作。",
    business3Title: "产品定制开发",
    business3Copy: "为具体社区、行业或本地服务场景设计并开发独立网站或工具。",
    businessNote1: "English: partnerships, local merchant promotion, platform cooperation and custom product development.",
    businessNote2: "Español: colaboraciones comerciales, promoción para negocios locales, cooperación de plataforma y desarrollo de productos a medida.",
    processTitle: "从需求到上线运营",
    process1Title: "识别场景",
    process1Copy: "先看用户每天真正要完成什么事，再决定产品应该长什么样。",
    process2Title: "搭建功能",
    process2Copy: "围绕发布、搜索、筛选、账号和管理，把核心链路做完整。",
    process3Title: "优化体验",
    process3Copy: "让手机端访问、微信分享、城市分类和信息浏览都更顺手。",
    process4Title: "上线迭代",
    process4Copy: "上线后继续根据用户反馈、内容质量和运营节奏调整产品。",
    contactTitle: "商务合作，或想做一个真正有人用的产品？",
    contactCopy: "欢迎联系老王跟小宋工作室。我们可以从商家推广、平台合作、社区项目或一个本地服务场景开始，把想法推进到可上线、可运营的产品。",
    wechatLabel: "微信 WeChat",
    mobileProduct: "产品",
    mobileBusiness: "合作",
    mobileContact: "联系"
  },
  en: {
    brand: "Wang & Song Studio",
    navServices: "Services",
    navWork: "Work",
    navBusiness: "Partnerships",
    navProcess: "Process",
    navContact: "Contact",
    heroTitle: "We build<br>España Life",
    heroCopy: "A local service platform for the Chinese community in Spain, bringing jobs, housing, business transfers, second-hand listings and everyday services into one clear product.",
    heroSubcopy: "Language selected: English.",
    visitProduct: "Visit Product",
    viewCase: "View Case",
    introTitle: "Products shaped by real community needs.",
    introCopy: "España Life serves Chinese users living, working and running businesses in Spain. We turn high-frequency local information into a product that is easy to publish, search and filter.",
    introPoint1: "<strong>Studio Focus</strong>Practical web products for local communities, from strategy and interface to launch and iteration.",
    introPoint2: "<strong>Commercial Fit</strong>Built for real use: local discovery, merchant visibility, community information and repeatable operations.",
    servicesTitle: "More than a website",
    service1Title: "Product Planning",
    service1Copy: "We clarify users, scenarios and publishing flows before deciding what should be built first.",
    service2Title: "Web Development",
    service2Copy: "We build accessible, shareable and maintainable web products with strong mobile experiences.",
    service3Title: "Information Systems",
    service3Copy: "Categories, filters, posting, accounts, memberships and listing management for local service platforms.",
    service4Title: "Growth Execution",
    service4Copy: "We consider WeChat sharing, search visibility, campaign entry points and conversion paths.",
    workTitle: "España Life",
    caseTitle: "Local service platform for Chinese users in Spain",
    caseCopy: "A classified information product covering jobs, housing, business transfers, second-hand goods and everyday services.",
    caseSubcopy: "Built to connect local information, merchant services and community needs.",
    openProduct: "Open Product",
    rowJobs: "Jobs & Hiring",
    rowHousing: "Housing",
    rowBusiness: "Business Transfers",
    rowMarketplace: "Second-hand & Services",
    businessTitle: "Business Partnerships",
    businessCopy: "For local businesses, service providers, community organizations and project owners in Spain, we support listings, brand visibility, platform partnerships and custom digital products.",
    business1Title: "Merchant Promotion",
    business1Copy: "Give local businesses a clearer way to reach the Chinese community in Spain.",
    business2Title: "Platform Partnerships",
    business2Copy: "Collaborate around jobs, real estate, local services, business transfers and community traffic.",
    business3Title: "Custom Product Development",
    business3Copy: "Design and build independent websites or tools for specific communities, industries or local service scenarios.",
    businessNote1: "Available for partnerships, local merchant promotion, platform cooperation and custom product development.",
    businessNote2: "Spanish and Chinese community markets can be connected through focused digital products.",
    processTitle: "From need to launch",
    process1Title: "Identify the Scenario",
    process1Copy: "We start with what users actually need to do every day.",
    process2Title: "Build the Core",
    process2Copy: "Publishing, search, filters, accounts and management are built as a complete product path.",
    process3Title: "Improve the Experience",
    process3Copy: "Mobile access, sharing, city categories and browsing details are tuned for real users.",
    process4Title: "Launch and Iterate",
    process4Copy: "After launch, we continue improving based on feedback, content quality and operations.",
    contactTitle: "Business partnership or a product people will actually use?",
    contactCopy: "Contact Wang & Song Studio. We can start from merchant promotion, platform cooperation, community projects or a local service scenario.",
    wechatLabel: "WeChat",
    mobileProduct: "Product",
    mobileBusiness: "Partner",
    mobileContact: "Contact"
  },
  es: {
    brand: "Wang & Song Studio",
    navServices: "Servicios",
    navWork: "Proyectos",
    navBusiness: "Colaboración",
    navProcess: "Proceso",
    navContact: "Contacto",
    heroTitle: "Creamos<br>España Life",
    heroCopy: "Una plataforma local de servicios para la comunidad china en España, con empleo, vivienda, traspasos de negocios, segunda mano y servicios cotidianos en un solo producto.",
    heroSubcopy: "Idioma seleccionado: Español.",
    visitProduct: "Ver Producto",
    viewCase: "Ver Caso",
    introTitle: "Productos nacidos de necesidades reales de la comunidad.",
    introCopy: "España Life ayuda a usuarios chinos que viven, trabajan o tienen negocios en España. Convertimos información local frecuente en un producto fácil de publicar, buscar y filtrar.",
    introPoint1: "<strong>Enfoque del estudio</strong>Productos web prácticos para comunidades locales, desde la estrategia y la interfaz hasta el lanzamiento y la iteración.",
    introPoint2: "<strong>Valor comercial</strong>Diseñado para uso real: descubrimiento local, visibilidad para comercios, información comunitaria y operación continua.",
    servicesTitle: "Más que una página web",
    service1Title: "Planificación de Producto",
    service1Copy: "Definimos usuarios, escenarios y flujos de publicación antes de decidir qué construir primero.",
    service2Title: "Desarrollo Web",
    service2Copy: "Creamos productos web accesibles, compartibles y mantenibles, con una experiencia móvil sólida.",
    service3Title: "Sistemas de Información",
    service3Copy: "Categorías, filtros, publicación, cuentas, membresías y gestión de anuncios para plataformas locales.",
    service4Title: "Crecimiento",
    service4Copy: "Cuidamos la difusión en WeChat, la presencia en buscadores, las campañas y los caminos de conversión.",
    workTitle: "España Life",
    caseTitle: "Plataforma local de servicios para usuarios chinos en España",
    caseCopy: "Producto de anuncios clasificados que cubre empleo, vivienda, traspasos de negocios, segunda mano y servicios cotidianos.",
    caseSubcopy: "Creado para conectar información local, servicios comerciales y necesidades de la comunidad.",
    openProduct: "Abrir Producto",
    rowJobs: "Empleo",
    rowHousing: "Vivienda",
    rowBusiness: "Traspasos de Negocios",
    rowMarketplace: "Segunda Mano y Servicios",
    businessTitle: "Colaboración Comercial",
    businessCopy: "Para comercios locales, proveedores de servicios, organizaciones comunitarias y proyectos en España, ofrecemos anuncios, visibilidad de marca, cooperación de plataforma y productos digitales a medida.",
    business1Title: "Promoción para Comercios",
    business1Copy: "Ayudamos a negocios locales a llegar con más claridad a la comunidad china en España.",
    business2Title: "Cooperación de Plataforma",
    business2Copy: "Colaboramos en empleo, vivienda, servicios locales, traspasos de negocios y tráfico comunitario.",
    business3Title: "Desarrollo a Medida",
    business3Copy: "Diseñamos y desarrollamos sitios web o herramientas para comunidades, sectores o servicios locales específicos.",
    businessNote1: "Disponibles para colaboraciones comerciales, promoción local, cooperación de plataforma y desarrollo a medida.",
    businessNote2: "Conectamos mercados locales españoles y comunidades chinas mediante productos digitales enfocados.",
    processTitle: "De la necesidad al lanzamiento",
    process1Title: "Identificar el Escenario",
    process1Copy: "Empezamos por lo que los usuarios realmente necesitan hacer cada día.",
    process2Title: "Construir el Núcleo",
    process2Copy: "Publicación, búsqueda, filtros, cuentas y gestión forman una ruta de producto completa.",
    process3Title: "Mejorar la Experiencia",
    process3Copy: "Optimizamos acceso móvil, compartir, categorías por ciudad y navegación de información.",
    process4Title: "Lanzar e Iterar",
    process4Copy: "Después del lanzamiento, mejoramos según comentarios, calidad del contenido y operación.",
    contactTitle: "¿Colaboración comercial o un producto que la gente use de verdad?",
    contactCopy: "Contacta con Wang & Song Studio. Podemos empezar desde promoción para comercios, cooperación de plataforma, proyectos comunitarios o un servicio local.",
    wechatLabel: "WeChat",
    mobileProduct: "Producto",
    mobileBusiness: "Colaborar",
    mobileContact: "Contacto"
  }
};

const languageNames = {
  zh: "zh-CN",
  en: "en",
  es: "es"
};

function applyLanguage(lang) {
  const dictionary = translations[lang] || translations.zh;

  document.documentElement.lang = languageNames[lang] || "zh-CN";
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) {
      element.innerHTML = dictionary[key];
    }
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    const isActive = button.dataset.lang === lang;
    button.classList.toggle("active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  localStorage.setItem("studioLanguage", lang);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

applyLanguage(localStorage.getItem("studioLanguage") || "zh");
